### PR TITLE
Some small changes

### PR DESCRIPTION
**Pull request by dfm**
I'm still going through this and I'll update this as I have more comments. Overall things look excellent.

- I disagree with most of the uses of "precision" in the text. Most of the time, we actually want to use "accuracy" to describe the difference between the computed and expected values. There are places where "precision" is right (when there is numerical noise causing the inaccuracy) and the argument could be made that I've over-corrected in a few places. But some of the uses of "precision" are definitely wrong!

### CODE REVIEW

**Comment by rodluger** [comment]
Cool. I agree in principle, although all my tests quoting errors < 1 ppb are (I think) actually measuring the *precision* of the algorithm. I don't have an *accurate* estimate of the flux at that level to compare to (numerical integration on the grid accurate to < 1 ppb would take hours), so instead I am measuring the variance of the algorithm when I perturb the inputs at the machine level. I'm *assuming* it's accurate based on how it agrees with the numerical result to within the accuracy of the latter, but I can only technically measure its precision. Do you agree?

**Comment by dfm** [comment]
Fair enough! So I would change some of those back, but not all. We're still arguing that we have an *accurate* algorithm. I'll go through and audit!

**Comment by dfm** [comment]
OK - I changed most occurrences back now that I actually understand what is going on. I added a sentence to emphasize this, but feel free to rewrite or skip it! I think this is an awesome paper, and I really don't have anything else to add!!

**Comment by rodluger** [comment]
Awesome, thanks!

**Pull request merged**
